import { NumberSymbol } from "@angular/common";

export interface ContactenosDTO{
  Id?:number,
  IdContactoPortal?:number,
  Nombres:string,
  Apellidos:string,
  Correo1:string,
  Correo2?:string,
  Fijo?:string,
  Movil:string,
  IdAreaFormacion?:number,
  IdCargo?:number,
  IdAreaTrabajo?:number,
  IdIndustria?:number,
  IdPais?:number,
  IdRegion?:number,
  Empresa?:string,
  Ciudad?:string,
  Direccion?:string,
  IpAddress?:string,
  FechaCreacion?:Date,
  FechaModificacion?:Date,
  IdTipoEstado?:number,
  IdTipoFormulario?:number,
  Interesado?:boolean,
  Terminos?:boolean,
  IdAlumno?:number,
  NumeroDocumento?:string,
  Comentario?:string,

  IdTipoDocumentoPersonal?:number,
  IdTipoDocumento?:any,
  IdSexo?:number,
  FechaNacimiento?:Date,
  Genero?:string,

  IdContactoPortalSegmento?:any,
  IdCampania?:number,
  IdCategoriaDato?:number,
  if_url?:string,
  url_anterior?:string,
  TextoBoton?:string,
  TipoRespuesta?:string,
  TipoFormulario?:string,
  NombrePrograma?:string,
  NombreOrigen?:string,
  NombreFormulario?:string,
  NombreCentroCosto?:string,
  IdTipoDato?:number,  //mkt.T_TipoDato
  IdFaseOportunidad?:number,  //pla.T_FaseOportunidad
  IdFormularioPublicidad?:number,  // formualrios de prublicidad
  //
  IdTiempoCapacitacion?:number,
  ProbabilidadCargo?:boolean,
  ProbabilidadAreaFormacion?:boolean,
  ProbabilidadAreaTrabajo?:boolean,
  ProbabilidadIndustria?:boolean,
  IdInteraccionPublicidad?:number,
  UrlOrigen?:string,
  IdCentroCosto?:number,
  IdPespecifico?:number,
  UrlBrochure?:string,
  UrlImagen?:string,
  NombreCampania?:string,
  testeo_ab?:string,

  //whitepaper
  IdArticulo?:number,
  NombreWhitePaper?:string,
  urlWhitePaper?:string,
}
